In [5]:
from nba_api.stats.endpoints import playercareerstats, leagueleaders
from nba_api.stats.static import players, teams

# data
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [6]:
career = playercareerstats.PlayerCareerStats(player_id='203999') # Nikola Jokic
nikola_df = career.get_data_frames()[0]

In [7]:
nikola_df

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,203999,2015-16,00,1610612743,DEN,21.0,80,55,1733.0,307,...,0.811,181,379,560,189,79,50,104,208,796
1,203999,2016-17,00,1610612743,DEN,22.0,73,59,2038.0,494,...,0.825,212,506,718,359,61,55,171,214,1221
2,203999,2017-18,00,1610612743,DEN,23.0,75,73,2443.0,504,...,0.850,195,608,803,458,90,61,210,212,1385
3,203999,2018-19,00,1610612743,DEN,24.0,80,80,2504.0,616,...,0.821,228,637,865,580,108,55,248,228,1604
4,203999,2019-20,00,1610612743,DEN,25.0,73,73,2335.0,565,...,0.817,166,545,711,512,85,44,226,222,1456
5,203999,2020-21,00,1610612743,DEN,26.0,72,72,2488.0,732,...,0.868,205,575,780,599,95,48,222,192,1898
6,203999,2021-22,00,1610612743,DEN,27.0,74,74,2476.0,764,...,0.810,206,813,1019,584,109,63,281,191,2004
7,203999,2022-23,00,1610612743,DEN,28.0,69,69,2323.0,646,...,0.822,167,650,817,678,87,47,247,174,1690
8,203999,2023-24,00,1610612743,DEN,29.0,79,79,2737.0,822,...,0.817,223,753,976,708,108,68,237,194,2085
9,203999,2024-25,00,1610612743,DEN,30.0,67,67,2461.0,763,...,0.803,193,664,857,685,119,44,223,152,2007

### Get list of active players.

In [8]:
current_players = pd.DataFrame(players.get_active_players())
current_players

          id         full_name first_name last_name  is_active
0    1630173  Precious Achiuwa   Precious   Achiuwa       True
1     203500      Steven Adams     Steven     Adams       True
2    1628389       Bam Adebayo        Bam   Adebayo       True
3    1630534      Ochai Agbaji      Ochai    Agbaji       True
4    1630583      Santi Aldama      Santi    Aldama       True
..       ...               ...        ...       ...        ...
539   203469       Cody Zeller       Cody    Zeller       True
540  1627826       Ivica Zubac      Ivica     Zubac       True
541  1641783  Tristan da Silva    Tristan  da Silva       True
542  1628427     Vlatko Čančar     Vlatko    Čančar       True
543   203967       Dario Šarić      Dario     Šarić       True

[544 rows x 5 columns]

### Simple Criteria for Superstar players.
Scored atleast:
- 20 pts
- 4 Asst
- 4 Rebounds
- 3 Steals
- PER of 15.

### EFF of 13 or greater.

Current Players

In [9]:
per_leaders = leagueleaders.LeagueLeaders(stat_category_abbreviation='EFF').get_data_frames()[0]
per_leaders.head(10)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,...,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,203999,1,Nikola Jokić,1610612743,DEN,67,2461,763,1323,0.577,...,857,685,119,44,223,152,2007,2844,3.07,0.53
1,1628983,2,Shai Gilgeous-Alexander,1610612760,OKC,75,2561,846,1630,0.519,...,373,480,131,76,182,159,2442,2470,2.64,0.72
2,203507,3,Giannis Antetokounmpo,1610612749,MIL,64,2188,762,1265,0.602,...,763,403,56,74,203,154,1953,2285,1.99,0.28
3,1626157,4,Karl-Anthony Towns,1610612752,NYK,70,2445,615,1175,0.523,...,896,215,69,49,185,241,1700,2116,1.16,0.37
4,1627734,5,Domantas Sabonis,1610612758,SAC,66,2292,498,847,0.588,...,917,400,44,24,194,218,1266,2037,2.06,0.23
5,1627826,6,Ivica Zubac,1610612746,LAC,76,2473,553,886,0.624,...,951,196,52,89,122,165,1257,2010,1.61,0.43
6,1628369,7,Jayson Tatum,1610612738,BOS,70,2544,645,1426,0.452,...,608,418,75,37,207,151,1884,1954,2.02,0.36
7,2544,8,LeBron James,1610612747,LAL,67,2351,626,1220,0.513,...,528,561,67,39,251,95,1641,1921,2.23,0.27
8,1630578,9,Alperen Sengun,1610612745,HOU,75,2371,560,1129,0.496,...,781,368,84,60,194,208,1437,1835,1.90,0.43
9,201935,10,James Harden,1610612746,LAC,75,2623,492,1222,0.403,...,426,645,112,52,325,154,1684,1795,1.99,0.34

In [10]:
per_leaders['EFF_PER_GAME'] = per_leaders['EFF']/per_leaders['GP'] # EFF / games played
per_leaders.head(10)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,...,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV,EFF_PER_GAME
0,203999,1,Nikola Jokić,1610612743,DEN,67,2461,763,1323,0.577,...,685,119,44,223,152,2007,2844,3.07,0.53,42.447761
1,1628983,2,Shai Gilgeous-Alexander,1610612760,OKC,75,2561,846,1630,0.519,...,480,131,76,182,159,2442,2470,2.64,0.72,32.933333
2,203507,3,Giannis Antetokounmpo,1610612749,MIL,64,2188,762,1265,0.602,...,403,56,74,203,154,1953,2285,1.99,0.28,35.703125
3,1626157,4,Karl-Anthony Towns,1610612752,NYK,70,2445,615,1175,0.523,...,215,69,49,185,241,1700,2116,1.16,0.37,30.228571
4,1627734,5,Domantas Sabonis,1610612758,SAC,66,2292,498,847,0.588,...,400,44,24,194,218,1266,2037,2.06,0.23,30.863636
5,1627826,6,Ivica Zubac,1610612746,LAC,76,2473,553,886,0.624,...,196,52,89,122,165,1257,2010,1.61,0.43,26.447368
6,1628369,7,Jayson Tatum,1610612738,BOS,70,2544,645,1426,0.452,...,418,75,37,207,151,1884,1954,2.02,0.36,27.914286
7,2544,8,LeBron James,1610612747,LAL,67,2351,626,1220,0.513,...,561,67,39,251,95,1641,1921,2.23,0.27,28.671642
8,1630578,9,Alperen Sengun,1610612745,HOU,75,2371,560,1129,0.496,...,368,84,60,194,208,1437,1835,1.90,0.43,24.466667
9,201935,10,James Harden,1610612746,LAC,75,2623,492,1222,0.403,...,645,112,52,325,154,1684,1795,1.99,0.34,23.933333

In [11]:
high_per_players = per_leaders[per_leaders['EFF_PER_GAME'] >= 13]
high_per_players.head(10)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,...,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV,EFF_PER_GAME
0,203999,1,Nikola Jokić,1610612743,DEN,67,2461,763,1323,0.577,...,685,119,44,223,152,2007,2844,3.07,0.53,42.447761
1,1628983,2,Shai Gilgeous-Alexander,1610612760,OKC,75,2561,846,1630,0.519,...,480,131,76,182,159,2442,2470,2.64,0.72,32.933333
2,203507,3,Giannis Antetokounmpo,1610612749,MIL,64,2188,762,1265,0.602,...,403,56,74,203,154,1953,2285,1.99,0.28,35.703125
3,1626157,4,Karl-Anthony Towns,1610612752,NYK,70,2445,615,1175,0.523,...,215,69,49,185,241,1700,2116,1.16,0.37,30.228571
4,1627734,5,Domantas Sabonis,1610612758,SAC,66,2292,498,847,0.588,...,400,44,24,194,218,1266,2037,2.06,0.23,30.863636
5,1627826,6,Ivica Zubac,1610612746,LAC,76,2473,553,886,0.624,...,196,52,89,122,165,1257,2010,1.61,0.43,26.447368
6,1628369,7,Jayson Tatum,1610612738,BOS,70,2544,645,1426,0.452,...,418,75,37,207,151,1884,1954,2.02,0.36,27.914286
7,2544,8,LeBron James,1610612747,LAL,67,2351,626,1220,0.513,...,561,67,39,251,95,1641,1921,2.23,0.27,28.671642
8,1630578,9,Alperen Sengun,1610612745,HOU,75,2371,560,1129,0.496,...,368,84,60,194,208,1437,1835,1.90,0.43,24.466667
9,201935,10,James Harden,1610612746,LAC,75,2623,492,1222,0.403,...,645,112,52,325,154,1684,1795,1.99,0.34,23.933333

In [12]:
high_per_players.tail(10)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,...,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV,EFF_PER_GAME
273,203954,272,Joel Embiid,1610612755,PHI,19,574,140,315,0.444,...,85,14,18,62,42,452,467,1.37,0.23,24.578947
274,1641706,275,Brandon Miller,1610612766,CHA,27,924,198,491,0.403,...,98,29,20,76,74,568,466,1.29,0.38,17.259259
277,1630560,278,Cam Thomas,1610612751,BKN,25,781,199,454,0.438,...,94,15,2,62,44,599,458,1.52,0.24,18.320000
287,1629021,288,Moritz Wagner,1610612753,ORL,30,564,140,249,0.562,...,42,24,12,49,55,386,423,0.86,0.49,14.100000
307,1627742,308,Brandon Ingram,1610612761,TOR,18,595,155,333,0.465,...,93,16,11,69,45,400,365,1.35,0.23,20.277778
317,1627763,318,Malcolm Brogdon,1610612764,WAS,24,564,104,240,0.433,...,98,13,5,38,30,305,327,2.58,0.34,13.625000
365,1629684,366,Grant Williams,1610612766,CHA,16,479,54,123,0.439,...,37,18,13,28,46,166,213,1.32,0.64,13.312500
446,1629643,447,Chuma Okeke,1610612739,CLE,7,171,18,33,0.545,...,13,5,3,3,5,48,93,4.33,1.67,13.285714
458,1631166,458,Drew Timme,1610612751,BKN,5,125,25,49,0.510,...,9,4,1,8,9,58,66,1.13,0.50,13.200000
509,1642368,508,N'Faly Dante,1610612745,HOU,1,19,4,6,0.667,...,1,0,2,1,4,10,18,1.00,0.00,18.000000

In [13]:
high_per_players.to_csv(r'./current_superstars_2024_25.csv')

Previous Seasons

I'll use stars from 1996 to 2024.

In [14]:
season_list = [f"{year}-{str(year+1)[-2:]}" for year in range(1995, 2025)]

In [15]:
season_list

['1995-96',
 '1996-97',
 '1997-98',
 '1998-99',
 '1999-00',
 '2000-01',
 '2001-02',
 '2002-03',
 '2003-04',
 '2004-05',
 '2005-06',
 '2006-07',
 '2007-08',
 '2008-09',
 '2009-10',
 '2010-11',
 '2011-12',
 '2012-13',
 '2013-14',
 '2014-15',
 '2015-16',
 '2016-17',
 '2017-18',
 '2018-19',
 '2019-20',
 '2020-21',
 '2021-22',
 '2022-23',
 '2023-24',
 '2024-25']

In [16]:
# This is an example; 2018-19.
old_leaders = leagueleaders.LeagueLeaders(season=season_list[5], stat_category_abbreviation='EFF').get_data_frames()[0]
old_leaders.head(10)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,...,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,406,1,Shaquille O'Neal,1610612747,LAL,74,2924,813,1422,0.572,...,940,277,47,204,218,256,2125,2293,1.27,0.22
1,708,2,Kevin Garnett,1610612750,MIN,81,3202,704,1475,0.477,...,921,401,111,145,230,204,1784,2251,1.74,0.48
2,1495,3,Tim Duncan,1610612759,SAS,82,3174,702,1406,0.499,...,997,245,70,192,242,247,1820,2125,1.01,0.29
3,252,4,Karl Malone,1610612762,UTA,81,2895,670,1345,0.498,...,669,361,93,62,244,216,1878,2004,1.48,0.38
4,185,5,Chris Webber,1610612758,SAC,70,2836,786,1635,0.481,...,777,294,93,118,195,226,1898,1999,1.51,0.48
5,1717,6,Dirk Nowitzki,1610612742,DAL,82,3125,591,1247,0.474,...,754,173,79,101,156,245,1784,1992,1.11,0.51
6,1503,7,Tracy McGrady,1610612753,ORL,77,3087,788,1724,0.457,...,580,352,116,118,198,160,2065,1940,1.78,0.59
7,952,8,Antoine Walker,1610612738,BOS,81,3396,711,1720,0.413,...,719,445,138,49,301,251,1892,1834,1.48,0.46
8,1890,9,Shawn Marion,1610612756,PHX,79,2857,557,1160,0.480,...,848,160,132,108,129,211,1369,1830,1.24,1.02
9,951,10,Ray Allen,1610612749,MIL,82,3129,628,1309,0.480,...,428,374,124,20,204,192,1806,1823,1.83,0.61

In [17]:
def player_info(player_id):
    return playercareerstats.PlayerCareerStats(player_id=player_id).get_data_frames()[0]

In [18]:
harden_info = player_info('201935')
harden_info

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,201935,2009-10,00,1610612760,OKC,20.0,76,0,1738.0,233,...,0.808,47,197,244,137,80,20,106,200,753
1,201935,2010-11,00,1610612760,OKC,21.0,82,5,2189.0,298,...,0.843,42,213,255,176,92,24,106,207,998
2,201935,2011-12,00,1610612760,OKC,22.0,62,2,1946.0,309,...,0.846,30,222,252,229,62,15,137,150,1044
3,201935,2012-13,00,1610612745,HOU,23.0,78,78,2985.0,585,...,0.851,62,317,379,455,142,38,295,178,2023
4,201935,2013-14,00,1610612745,HOU,24.0,73,73,2777.0,549,...,0.866,61,283,344,446,115,29,265,177,1851
5,201935,2014-15,00,1610612745,HOU,25.0,81,81,2981.0,647,...,0.868,75,384,459,565,154,60,321,208,2217
6,201935,2015-16,00,1610612745,HOU,26.0,82,82,3125.0,710,...,0.860,63,438,501,612,139,51,374,229,2376
7,201935,2016-17,00,1610612745,HOU,27.0,81,81,2947.0,674,...,0.847,95,564,659,907,121,38,464,215,2356
8,201935,2017-18,00,1610612745,HOU,28.0,72,72,2551.0,651,...,0.858,41,348,389,630,126,50,315,169,2191
9,201935,2018-19,00,1610612745,HOU,29.0,78,78,2867.0,843,...,0.879,66,452,518,586,158,58,387,244,2818
10,201935,2019-20,00,1610612745,HOU,30.0,68,68,2483.0,672,...,0.865,70,376,446,512,125,60,308,227,2335
11,201935,2020-21,00,1610612745,HOU,31.0,8,8,290.0,60,...,0.883,5,36,41,83,7,6,34,14,198
12,201935,2020-21,00,1610612751,BKN,31.0,36,35,1319.0,282,...,0.856,30,277,307,392,46,27,143,85,885
13,201935,2020-21,00,0,TOT,31.0,44,43,1609.0,342,...,0.861,35,313,348,475,53,33,177,99,1083
14,201935,2021-22,00,1610612751,BKN,32.0,44,44,1627.0,292,...,0.869,42,309,351,447,56,31,212,105,990
15,201935,2021-22,00,1610612755,PHI,32.0,21,21,792.0,115,...,0.892,13,136,149,220,26,5,72,48,442
16,201935,2021-22,00,0,TOT,32.0,65,65,2420.0,407,...,0.877,55,445,500,667,82,36,284,153,1432
17,201935,2022-23,00,1610612755,PHI,33.0,58,58,2135.0,371,...,0.867,40,314,354,618,71,31,195,112,1216
18,201935,2023-24,00,1610612746,LAC,34.0,72,72,2470.0,352,...,0.878,34,335,369,614,77,57,185,127,1192
19,201935,2024-25,00,1610612746,LAC,35.0,75,75,2623.0,492,...,0.874,50,376,426,645,112,52,325,154,1684

Create a function that checks whether the player played for the team in previous year.

In [19]:
def was_traded(player_df, current_season, last_season):
    # player_df = player_info(player_id=player_id)
    current_team = player_df[player_df['SEASON_ID'] == current_season]['TEAM_ID'].iloc[0]
    last_season_team = player_df[player_df['SEASON_ID'] == last_season]['TEAM_ID'].iloc[0]
    if current_team == last_season_team:
        player_df['CHANGED_FRANCHISE'] = True
    elif current_team != last_season_team:
        player_df['CHANGED_FRANCHISE'] = False

In [20]:
# def was_traded(player_df, season_list):
#     # player_df = player_info(player_id=player_id)
#     sorted_seasons = sorted(season_list)
#     player_df = player_df.sort_values('SEASON_ID')

#     player_df['CHANGED_FRANCHISE'] = False

#     for i in range(1, len(sorted_seasons)):
#         current_season = sorted_seasons[i]
#         prev_season = sorted_seasons[i-1]

#         if not season_list[i] in player_df['SEASON_ID']:
#             pass
#         elif season_list[i] in player_df['SEASON_ID'] & season_list[i-1] not in player_df['SEASON_ID']:
#             player_df['CHANGED_FRANCHISE'] = False
#         elif season_list[i] in player_df['SEASON_ID'] & season_list[i-1] in player_df['SEASON_ID']:
#             current_team = player_df[player_df['SEASON_ID'] == season_list[i]]['TEAM_ID'].iloc[0]
#             last_season_team = player_df[player_df['SEASON_ID'] == season_list[i-1]]['TEAM_ID'].iloc[0]
#             if current_team == last_season_team:
#                 player_df['CHANGED_FRANCHISE'] = True
#             elif current_team != last_season_team:
#                 player_df['CHANGED_FRANCHISE'] = False

In [21]:
def was_traded(player_df, season_list):
    # Sort seasons chronologically
    sorted_seasons = sorted(season_list)
    player_df = player_df.sort_values('SEASON_ID')
    
    # Initialize column to track trades
    player_df['CHANGED_FRANCHISE'] = False
    
    for i in range(1, len(sorted_seasons)):  # Start from 1 to avoid index -1
        current_season = sorted_seasons[i]
        prev_season = sorted_seasons[i-1]
        
        # Check if player participated in both seasons
        current_in_df = current_season in player_df['SEASON_ID'].values
        prev_in_df = prev_season in player_df['SEASON_ID'].values
        
        if current_in_df and prev_in_df:
            current_team = player_df[player_df['SEASON_ID'] == current_season]['TEAM_ID'].iloc[0]
            prev_team = player_df[player_df['SEASON_ID'] == prev_season]['TEAM_ID'].iloc[0]
            
            if current_team != prev_team:
                player_df.loc[player_df['SEASON_ID'] == current_season, 'CHANGED_FRANCHISE'] = True
                
        elif current_in_df and not prev_in_df:
            # Handle rookies (no prior season)
            player_df.loc[player_df['SEASON_ID'] == current_season, 'CHANGED_FRANCHISE'] = False
    
    return player_df

In [22]:
was_traded(harden_info, season_list)

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,CHANGED_FRANCHISE
0,201935,2009-10,00,1610612760,OKC,20.0,76,0,1738.0,233,...,47,197,244,137,80,20,106,200,753,False
1,201935,2010-11,00,1610612760,OKC,21.0,82,5,2189.0,298,...,42,213,255,176,92,24,106,207,998,False
2,201935,2011-12,00,1610612760,OKC,22.0,62,2,1946.0,309,...,30,222,252,229,62,15,137,150,1044,False
3,201935,2012-13,00,1610612745,HOU,23.0,78,78,2985.0,585,...,62,317,379,455,142,38,295,178,2023,True
4,201935,2013-14,00,1610612745,HOU,24.0,73,73,2777.0,549,...,61,283,344,446,115,29,265,177,1851,False
5,201935,2014-15,00,1610612745,HOU,25.0,81,81,2981.0,647,...,75,384,459,565,154,60,321,208,2217,False
6,201935,2015-16,00,1610612745,HOU,26.0,82,82,3125.0,710,...,63,438,501,612,139,51,374,229,2376,False
7,201935,2016-17,00,1610612745,HOU,27.0,81,81,2947.0,674,...,95,564,659,907,121,38,464,215,2356,False
8,201935,2017-18,00,1610612745,HOU,28.0,72,72,2551.0,651,...,41,348,389,630,126,50,315,169,2191,False
9,201935,2018-19,00,1610612745,HOU,29.0,78,78,2867.0,843,...,66,452,518,586,158,58,387,244,2818,False
10,201935,2019-20,00,1610612745,HOU,30.0,68,68,2483.0,672,...,70,376,446,512,125,60,308,227,2335,False
11,201935,2020-21,00,1610612745,HOU,31.0,8,8,290.0,60,...,5,36,41,83,7,6,34,14,198,False
12,201935,2020-21,00,1610612751,BKN,31.0,36,35,1319.0,282,...,30,277,307,392,46,27,143,85,885,False
13,201935,2020-21,00,0,TOT,31.0,44,43,1609.0,342,...,35,313,348,475,53,33,177,99,1083,False
14,201935,2021-22,00,1610612751,BKN,32.0,44,44,1627.0,292,...,42,309,351,447,56,31,212,105,990,True
15,201935,2021-22,00,1610612755,PHI,32.0,21,21,792.0,115,...,13,136,149,220,26,5,72,48,442,True
16,201935,2021-22,00,0,TOT,32.0,65,65,2420.0,407,...,55,445,500,667,82,36,284,153,1432,True
17,201935,2022-23,00,1610612755,PHI,33.0,58,58,2135.0,371,...,40,314,354,618,71,31,195,112,1216,True
18,201935,2023-24,00,1610612746,LAC,34.0,72,72,2470.0,352,...,34,335,369,614,77,57,185,127,1192,True
19,201935,2024-25,00,1610612746,LAC,35.0,75,75,2623.0,492,...,50,376,426,645,112,52,325,154,1684,False

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,201935,2009-10,00,1610612760,OKC,20.0,76,0,1738.0,233,...,0.808,47,197,244,137,80,20,106,200,753
1,201935,2010-11,00,1610612760,OKC,21.0,82,5,2189.0,298,...,0.843,42,213,255,176,92,24,106,207,998
2,201935,2011-12,00,1610612760,OKC,22.0,62,2,1946.0,309,...,0.846,30,222,252,229,62,15,137,150,1044
3,201935,2012-13,00,1610612745,HOU,23.0,78,78,2985.0,585,...,0.851,62,317,379,455,142,38,295,178,2023
4,201935,2013-14,00,1610612745,HOU,24.0,73,73,2777.0,549,...,0.866,61,283,344,446,115,29,265,177,1851
5,201935,2014-15,00,1610612745,HOU,25.0,81,81,2981.0,647,...,0.868,75,384,459,565,154,60,321,208,2217
6,201935,2015-16,00,1610612745,HOU,26.0,82,82,3125.0,710,...,0.860,63,438,501,612,139,51,374,229,2376
7,201935,2016-17,00,1610612745,HOU,27.0,81,81,2947.0,674,...,0.847,95,564,659,907,121,38,464,215,2356
8,201935,2017-18,00,1610612745,HOU,28.0,72,72,2551.0,651,...,0.858,41,348,389,630,126,50,315,169,2191
9,201935,2018-19,00,1610612745,HOU,29.0,78,78,2867.0,843,...,0.879,66,452,518,586,158,58,387,244,2818
10,201935,2019-20,00,1610612745,HOU,30.0,68,68,2483.0,672,...,0.865,70,376,446,512,125,60,308,227,2335
11,201935,2020-21,00,1610612745,HOU,31.0,8,8,290.0,60,...,0.883,5,36,41,83,7,6,34,14,198
12,201935,2020-21,00,1610612751,BKN,31.0,36,35,1319.0,282,...,0.856,30,277,307,392,46,27,143,85,885
13,201935,2020-21,00,0,TOT,31.0,44,43,1609.0,342,...,0.861,35,313,348,475,53,33,177,99,1083
14,201935,2021-22,00,1610612751,BKN,32.0,44,44,1627.0,292,...,0.869,42,309,351,447,56,31,212,105,990
15,201935,2021-22,00,1610612755,PHI,32.0,21,21,792.0,115,...,0.892,13,136,149,220,26,5,72,48,442
16,201935,2021-22,00,0,TOT,32.0,65,65,2420.0,407,...,0.877,55,445,500,667,82,36,284,153,1432
17,201935,2022-23,00,1610612755,PHI,33.0,58,58,2135.0,371,...,0.867,40,314,354,618,71,31,195,112,1216
18,201935,2023-24,00,1610612746,LAC,34.0,72,72,2470.0,352,...,0.878,34,335,369,614,77,57,185,127,1192
19,201935,2024-25,00,1610612746,LAC,35.0,75,75,2623.0,492,...,0.874,50,376,426,645,112,52,325,154,1684

In [18]:
was_traded('201935', '2024-25', '2023-24')

True

In [19]:
was_traded('201935', '2023-24', '2022-23')

False

In [ ]:
for i in range(len(season_list)):
    if not season_list[i] in player_info