In [10]:
from nba_api.stats.endpoints import playercareerstats, leagueleaders
from nba_api.stats.static import players, teams

# data
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [2]:
career = playercareerstats.PlayerCareerStats(player_id='203999') # Nikola Jokic
nikola_df = career.get_data_frames()[0]

In [3]:
nikola_df

   PLAYER_ID SEASON_ID LEAGUE_ID     TEAM_ID  ... BLK  TOV   PF   PTS
0     203999   2015-16        00  1610612743  ...  50  104  208   796
1     203999   2016-17        00  1610612743  ...  55  171  214  1221
2     203999   2017-18        00  1610612743  ...  61  210  212  1385
3     203999   2018-19        00  1610612743  ...  55  248  228  1604
4     203999   2019-20        00  1610612743  ...  44  226  222  1456
5     203999   2020-21        00  1610612743  ...  48  222  192  1898
6     203999   2021-22        00  1610612743  ...  63  281  191  2004
7     203999   2022-23        00  1610612743  ...  47  247  174  1690
8     203999   2023-24        00  1610612743  ...  68  237  194  2085
9     203999   2024-25        00  1610612743  ...  36  177  117  1572

[10 rows x 27 columns]

### Get list of active players.

In [7]:
current_players = pd.DataFrame(players.get_active_players())
current_players

          id         full_name first_name last_name  is_active
0    1630173  Precious Achiuwa   Precious   Achiuwa       True
1     203500      Steven Adams     Steven     Adams       True
2    1628389       Bam Adebayo        Bam   Adebayo       True
3    1630534      Ochai Agbaji      Ochai    Agbaji       True
4    1630583      Santi Aldama      Santi    Aldama       True
..       ...               ...        ...       ...        ...
539   203469       Cody Zeller       Cody    Zeller       True
540  1627826       Ivica Zubac      Ivica     Zubac       True
541  1641783  Tristan da Silva    Tristan  da Silva       True
542  1628427     Vlatko Čančar     Vlatko    Čančar       True
543   203967       Dario Šarić      Dario     Šarić       True

[544 rows x 5 columns]

### Simple Criteria for Superstar players.
Scored atleast:
- 20 pts
- 4 Asst
- 4 Rebounds
- 3 Steals
- PER of 15.

### EFF of 13 or greater.

Current Players

In [11]:
per_leaders = leagueleaders.LeagueLeaders(stat_category_abbreviation='EFF').get_data_frames()[0]
per_leaders.head(10)

   PLAYER_ID  RANK                   PLAYER  ...   EFF AST_TOV  STL_TOV
0     203999     1             Nikola Jokić  ...  2283    3.19     0.54
1    1628983     2  Shai Gilgeous-Alexander  ...  1905    2.37     0.72
2    1627734     3         Domantas Sabonis  ...  1768    2.07     0.20
3    1626157     4       Karl-Anthony Towns  ...  1669    1.26     0.39
4     203507     5    Giannis Antetokounmpo  ...  1657    1.76     0.22
5    1628369     6             Jayson Tatum  ...  1604    2.05     0.39
6       2544     7             LeBron James  ...  1581    2.18     0.23
7    1630595     8          Cade Cunningham  ...  1475    2.14     0.22
8    1627826     9              Ivica Zubac  ...  1458    1.45     0.46
9     202696    10           Nikola Vučević  ...  1421    1.98     0.51

[10 rows x 28 columns]

In [26]:
per_leaders['EFF_PER_GAME'] = per_leaders['EFF']/per_leaders['GP'] # EFF / games played
per_leaders.head(10)

   PLAYER_ID  RANK                   PLAYER  ...  AST_TOV STL_TOV  EFF_PER_GAME
0     203999     1             Nikola Jokić  ...     3.19    0.54     42.277778
1    1628983     2  Shai Gilgeous-Alexander  ...     2.37    0.72     32.844828
2    1627734     3         Domantas Sabonis  ...     2.07    0.20     31.571429
3    1626157     4       Karl-Anthony Towns  ...     1.26    0.39     31.490566
4     203507     5    Giannis Antetokounmpo  ...     1.76    0.22     35.255319
5    1628369     6             Jayson Tatum  ...     2.05    0.39     28.140351
6       2544     7             LeBron James  ...     2.18    0.23     29.277778
7    1630595     8          Cade Cunningham  ...     2.14    0.22     26.339286
8    1627826     9              Ivica Zubac  ...     1.45    0.46     25.578947
9     202696    10           Nikola Vučević  ...     1.98    0.51     25.375000

[10 rows x 29 columns]

In [27]:
high_per_players = per_leaders[per_leaders['EFF_PER_GAME'] >= 13]
high_per_players.head(10)

   PLAYER_ID  RANK                   PLAYER  ...  AST_TOV STL_TOV  EFF_PER_GAME
0     203999     1             Nikola Jokić  ...     3.19    0.54     42.277778
1    1628983     2  Shai Gilgeous-Alexander  ...     2.37    0.72     32.844828
2    1627734     3         Domantas Sabonis  ...     2.07    0.20     31.571429
3    1626157     4       Karl-Anthony Towns  ...     1.26    0.39     31.490566
4     203507     5    Giannis Antetokounmpo  ...     1.76    0.22     35.255319
5    1628369     6             Jayson Tatum  ...     2.05    0.39     28.140351
6       2544     7             LeBron James  ...     2.18    0.23     29.277778
7    1630595     8          Cade Cunningham  ...     2.14    0.22     26.339286
8    1627826     9              Ivica Zubac  ...     1.45    0.46     25.578947
9     202696    10           Nikola Vučević  ...     1.98    0.51     25.375000

[10 rows x 29 columns]

In [28]:
high_per_players.tail(10)

     PLAYER_ID  RANK             PLAYER  ...  AST_TOV STL_TOV  EFF_PER_GAME
235    1629021   235      Moritz Wagner  ...     0.86    0.49     14.100000
242     203114   243    Khris Middleton  ...     2.61    0.48     15.074074
256    1630560   257         Cam Thomas  ...     1.20    0.26     18.450000
258    1627742   259     Brandon Ingram  ...     1.35    0.23     20.277778
264    1631096   265      Chet Holmgren  ...     1.00    0.47     20.882353
274    1630193   275  Immanuel Quickley  ...     3.10    0.29     16.047619
278    1627763   279    Malcolm Brogdon  ...     2.58    0.34     13.625000
296     202695   297      Kawhi Leonard  ...     1.34    0.60     15.777778
335    1629684   335     Grant Williams  ...     1.32    0.64     13.312500
465    1631342   465    Daeqwon Plowden  ...     0.00    0.00     13.000000

[10 rows x 29 columns]

In [29]:
high_per_players.to_csv(r'./current_superstars_2024_25.csv')

Previous Seasons

I'll use stars from 1996 to 2024.

In [32]:
season_list = [
    '2023-24',
    '2022-23',
    '2021-22',
    '2020-21',
    '2019-20',
    '2018-19',
    '2017-18',
    '2016-17',
    '2015-16',
    '2014-15',
    '2013-14',
    '2012-13',
    '2011-12',
    '2010-11',
    '2009-10',
    '2008-09',
    '2007-08',
    '2006-07',
    '2005-06',
    '2004-05',
    '2003-04',
    '2002-03',
    '2001-02',
    '2000-01',
    '1999-00',
    '1998-99',
    '1997-98',
    '1996-97',
    '1995-96'
]

In [ ]:
# This is an example; 2018-19.
old_leaders = leagueleaders.LeagueLeaders(season=season_list[5], stat_category_abbreviation='EFF').get_data_frames()[0]
old_leaders.head(10)

   PLAYER_ID  RANK                 PLAYER  ...   EFF AST_TOV  STL_TOV
0     201935     1           James Harden  ...  2581    1.51     0.41
1     203507     2  Giannis Antetokounmpo  ...  2538    1.58     0.34
2    1626157     3     Karl-Anthony Towns  ...  2338    1.08     0.28
3     203999     4           Nikola Jokić  ...  2311    2.34     0.43
4     202696     5         Nikola Vučević  ...  2242    1.93     0.51
5     203497     6            Rudy Gobert  ...  2183    1.24     0.51
6     201142     7           Kevin Durant  ...  2178    2.03     0.26
7     203083     8         Andre Drummond  ...  2153    0.64     0.78
8     201566     9      Russell Westbrook  ...  2118    2.41     0.44
9     202331    10            Paul George  ...  2110    1.55     0.83

[10 rows x 28 columns]